Repository yverdon/geocity, pull requests merged in 2022-02, with the labels that each got.

#386 Migrate to PG13.
  docker-compose-demo.yml
  docker-compose-dev.yml
Labels: enhancement, database

#395 Upgrade to Pillow==9.0.0
  requirements.in
  requirements.txt
  requirements_dev.txt
Labels: enhancement, dependencies

#383 Yc 384
  permits/admin.py
  permits/forms.py
  permits/migrations/0059_add_order_field_to_works_object.py
  permits/models.py
  permits/tests/test_c_admin_site.py
Labels: enhancement

#412 Missing migration in YC-384
  permits/migrations/0059_add_order_field_to_works_object.py
Labels: enhancement
